name: afronski.pl
url: http://www.afronski.pl

description: Random thoughts from top of my head - afronski.pl

plugins:
  - jemoji

exclude: [
  "Gemfile",
  "Gemfile.lock",

  "blog.sublime-project",
  "blog.sublime-workspace",

  "Rakefile",

  "README.md",
  "License - MIT.md"
]
