name: afronski.pl
url: http://www.afronski.pl

description: Random thoughts from top of my head - afronski.pl

gems:
  - jemoji

emoji:
  dir: "/images/emoji"

highlighter: pygments

exclude: [
  "Gemfile",
  "Gemfile.lock",

  "blog.sublime-project",
  "blog.sublime-workspace",

  "Rakefile",

  "README.md",
  "License - MIT.md"
]
