markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Wojciech Gawroński
url: http://afronski.github.com
description: Personal technical blog powered by Jekyll and Zach Holman 'Left' theme.
twitter: afronski
github: afronski
gravatar_url: http://www.gravatar.com/avatar/d758847810384b49ef63c65d4c724507.png